# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts --no-audit --prefer-offline

# Copy source and build
COPY . .
RUN npm run build

# Default command
CMD ["node", "dist/index.js"]
